### ISSUE TITLE
f5-oslbaasv2-agent is not found

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#683] opened 2017-05-03 16:38 UTC
When installing the agent on an Ubuntu system, I cannot start the agent because the f5-oslbaasv2-agent script is not executable.

Workaround:
I need to chmod +x /etc/init.d/f5-oslbaasv2-agent

**Comment by mattgreene** [comment] 2017-05-05 21:20
@richbrowne Please rewrite using the proper issue template.

**Comment by dflanigan** [comment] 2017-05-24 17:54
duplicate of #735

**Comment by mattgreene** [comment] 2017-08-11 20:24
Issue #735 is closed.

**Closed by mattgreene** 2017-08-11 20:24 UTC
Labels: bug, duplicate, P2, S3
