### ISSUE TITLE
BIG-IP orphaned object support in the agent

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#731] opened 2017-05-19 16:07 UTC
#### OpenStack Release
Mitaka+

#### Description
An agent (single) associated with an environment and environment_group should periodically query neutron for all services associated with environment and environment_group. Any BIG-IP resources which are present which have no corresponding resources in neutron should be removed. 

No manual intervention should be needed to clean BIG-IP resources when an appropriate agent can communicate with neutron as a source of provisioning truth.

**Comment by richbrowne** [comment] 2017-12-05 15:44
This is a duplicate of #1095

**Closed by richbrowne** 2017-12-05 15:44 UTC
Labels: enhancement
