### ISSUE TITLE
Changing the admin_state_up of a pool member does not disable or enable a BIG-IP pool member

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#497] opened 2016-12-22 19:37 UTC
Similar to #493. Just making clear states the need to be fixed. Can mark as a duplicate.

Updating a pool member's admin_state through the LBaaSv2 API no longer updates the pool member enable or disabled state on the BIG-IP like it did in LBaaSv1.

#### Agent Version
All

#### Operating System
All

#### OpenStack Release
All

#### Description
Creating a pool member with admin_state_up attribute set to false does not create a BIG-IP pool member disabled.

Issuing a pool member update with admin_state_up attribute set to false does not disable a BIG-IP pool member. 

Issuing a pool member update with admin_state_up attribute set to true does not enable a BIG-IP pool member. 

#### Deployment
Any LBaaS deployment option.

**Comment by mattgreene** [comment] 2016-12-27 22:11
Duplicate of #493

**Closed** 2017-03-08 22:05 UTC
Labels: bug, duplicate, P2, S3
