### ISSUE TITLE
Need to replace stable/liberty branch references in test requirements files

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#486] opened 2016-12-15 20:55 UTC
Travis builds of liberty and related branches fail because of references to OpenStack stable/liberty. With the release of Newton, the stable/liberty branch was dropped. Now, git references to stable/liberty must be replaced with the liberty-eol tag. Known files with stable/liberty references include:
requirements.functest.txt
requirements.unittest.txt
test/functional/neutronless/service_object_rename/Dockerfiles/Dockerfile.xenial_liberty

**Comment by mattgreene** [comment] 2016-12-15 23:18
Duplicate of #485

**Closed** 2016-12-15 23:19 UTC
