### ISSUE TITLE
traffic_group distribution not working for scalen deployments

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-agent#321] opened 2016-09-20 21:00 UTC
Title: LBaaS agent in scalen mode does properly populate the traffic_group for listeners

Details: When the agent starts it collects all provisioned traffic groups on the BIG-IP, removing only the local_only traffic group. When a load_balancer is requested the traffic_group is intended to be populated from a the collected traffic_group list with tenant affinity. The traffic_group for the virtual_address is always /Common/traffic-group-1 always.

#### OpenStack Release
Mitaka

#### Description
It appears that the traffic_group is selected, but when passed to lbaas_builder.assure_service as a kwarg, nothing is done with it. When the listener_service attempts to get the traffic_group as an attribute of the loadbalancer service object. That attribute is not populate.

#### Agent Version
9.0.3

#### Operating System
RHOS on CentOS7

#### Deployment
LBaaS agent provisioned with 'scalen' mode configured to provision a three or more member sync-failover DSG. The devices should have at least 6 traffic groups configured with the traffic-group-1 removed or else renamed to see the behavior.

**Comment by jgruber** [comment] 2016-09-21 13:32
Escalating to Bug-Serverity-1-Critical ... Customer impacting now. 

The loadbalancer (listener is where the traffic group is set) does not apply the traffic group for the tenant, but the SNAT translation address does. This means that when failover is tested all connections using SNAT (which is all of them) are reset rather then failing to the next peer in the DSG.

**Comment by richbrowne** [comment] 2016-09-21 19:17
Have a fix for this.  Peer reviewed with Jeff.  Will push later today once I have implemented a test for it.

**Comment by alonsocamaro** [comment] 2016-09-22 10:08
Thanks all

It would be great if you could produce .debs. I would test if the issue is still reproducible. I'm going to be on PTO a couple of days. I will be back this Tuesday 27th EMEA time zone.

**Comment by richbrowne** [comment] 2016-09-22 16:34
John,

  I have a deb for you to try.  I don't know if you are already on
vacation, but this was a fast as I could get to it.

Regards,

Rich

**Comment by alonsocamaro** [comment] 2016-09-29 12:08
Hi Rich 

I would like to try the that .deb file. Please also include https://github.com/F5Networks/f5-openstack-agent/issues/304

Thanks

       Ulises

**Closed** 2016-09-30 19:20 UTC
Labels: bug, Bug-Serverity-1-Critical
