### ISSUE TITLE
Nodes are not deleted when pool/member is deleted.

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-agent#393] opened 2016-10-14 13:53 UTC
Nodes aren’t deleted if pool/member is deleted. Persistence profile, Pool members and Pool got deleted. VS is updated correctly. Nodes might become waste objects

**Comment by dflanigan** [comment] 2016-10-20 16:43
Suspect this is a duplicate of #315

**Comment by pjbreaux** [comment] 2016-11-17 16:36
Found the source of this while writing tempest scenario tests. When we delete a pool outright, instead of deleting members then the pool, the nodes remain because the agent does not check each member and corresponding node. The device however, does not remove the nodes even when a pool or pool members are deleted. If an OpenStack user deletes the pool, the members go away, but the code path traversed in the agent does not delete the members.

A new test exists in L7Policy tests in tempest which identifies this issue. It will fail until this is resolved.

**Closed** 2016-12-21 22:27 UTC
Labels: bug, duplicate, P2, S2
